name: Bounty Request
description: Request a analytics bounty
title: "[Bounty]: "
labels: ["bounty", "open"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request a bounty from the footprint community!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Questions
      description: Which business questions do you want to get answered?
      placeholder: Tell us what you need!
      value: "The sum of all DEX trades over the last month.."
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Technical Scope
      description: Do you need a dashboard, API access, etc?
      value: "A dashboard that pulls data each day.."
  - type: textarea
    id: prize
    attributes:
      label: Bounty Prize
      description: How do you intend to fund the bounty?
      value: "As part of the Footprint bounty program.."
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
